accounts: []
deployments:
  - name: kergiva-org-api
    replicas: ${replicas}
    image:
      repo: ${image_repo}/${image_name}
      tag: ${image_tag}
      pull_policy: Always
      pull_secret: ${image_pull_secret}
    environment_variables:
      DB_CONFIG_PATH: "/app/secrets/kergiva_db.yml"
    security:
      read_only_root_filesystem: true
      run_as_non_root: true
      run_as_user: 1000
      run_as_group: 1000
      drop_all_capabilities: true
      pod_fs_group: 1000
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    probes:
      liveness:
        path: /
        port: 5000
      readiness:
        path: /
        port: 5000
    volume_mounts:
      database-config: /app/secrets/
    endpoints:
      - name: ${service_name}
        container_port: ${service_port}
        protocol: ${service_protocol}
volumes:
  - name: nginx-config
    configMap:
      name: kergiva-org-api-site-configmap
  - name: site-config
    configMap:
      name: kergiva-org-api-site-configmap
  - name: cache-volume
    emptyDir: {}
  - name: run-volume
    emptyDir: {}
  - name: database-config
    secret:
      secretName: ${database_config_secret}
nodeSelector: {}
tolerations: []
affinity: {}